
package com.jerval.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "OrderServiceBean", targetNamespace = "http://ws.jerval.com", wsdlLocation = "http://127.0.0.1:8080/EJBWebService/OrderServiceBean?wsdl")
public class OrderServiceBean
    extends Service
{

    private final static URL ORDERSERVICEBEAN_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.jerval.ws.client.OrderServiceBean.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.jerval.ws.client.OrderServiceBean.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:8080/EJBWebService/OrderServiceBean?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8080/EJBWebService/OrderServiceBean?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ORDERSERVICEBEAN_WSDL_LOCATION = url;
    }

    public OrderServiceBean(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderServiceBean() {
        super(ORDERSERVICEBEAN_WSDL_LOCATION, new QName("http://ws.jerval.com", "OrderServiceBean"));
    }

    /**
     * 
     * @return
     *     returns OrderService
     */
    @WebEndpoint(name = "OrderServicePort")
    public OrderService getOrderServicePort() {
        return super.getPort(new QName("http://ws.jerval.com", "OrderServicePort"), OrderService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderService
     */
    @WebEndpoint(name = "OrderServicePort")
    public OrderService getOrderServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.jerval.com", "OrderServicePort"), OrderService.class, features);
    }

}
