
package com.jerval.ws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "OrderService", targetNamespace = "http://ws.jerval.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.jerval.ws.client.Order
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findOrder", targetNamespace = "http://ws.jerval.com", className = "com.jerval.ws.client.FindOrder")
    @ResponseWrapper(localName = "findOrderResponse", targetNamespace = "http://ws.jerval.com", className = "com.jerval.ws.client.FindOrderResponse")
    public Order findOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.jerval.ws.client.Order>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findOrders", targetNamespace = "http://ws.jerval.com", className = "com.jerval.ws.client.FindOrders")
    @ResponseWrapper(localName = "findOrdersResponse", targetNamespace = "http://ws.jerval.com", className = "com.jerval.ws.client.FindOrdersResponse")
    public List<Order> findOrders(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findUserName", targetNamespace = "http://ws.jerval.com", className = "com.jerval.ws.client.FindUserName")
    @ResponseWrapper(localName = "findUserNameResponse", targetNamespace = "http://ws.jerval.com", className = "com.jerval.ws.client.FindUserNameResponse")
    public String findUserName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
